# generated by datamodel-codegen:
#   filename:  platform-api.openapi.yaml
#   timestamp: 2026-03-24T06:16:22+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, ConfigDict


class CreateCaseRequest(BaseModel):
    title: str
    ownerTeamId: str


class CreateCaseResponse(BaseModel):
    caseId: str
    status: str


class CreateJdVersionRequest(BaseModel):
    rawText: str
    source: str


class CreateJdVersionResponse(BaseModel):
    jdVersionId: str
    versionNo: int
    status: str


class EvidenceRef(BaseModel):
    label: str
    excerpt: str


class StructuredFilters(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    location: Optional[Union[str, list[str]]] = None
    degree: Optional[int] = None
    schoolType: Optional[int] = None
    workExperienceRange: Optional[int] = None
    page: Optional[int] = None
    pageSize: Optional[int] = None


class ConditionPlanDraft(BaseModel):
    mustTerms: list[str]
    shouldTerms: list[str]
    excludeTerms: list[str]
    structuredFilters: StructuredFilters
    evidenceRefs: list[EvidenceRef]


class CreateKeywordDraftJobRequest(BaseModel):
    jdVersionId: str
    modelVersion: str
    promptVersion: str


class CreateKeywordDraftJobResponse(BaseModel):
    jobId: str
    status: str
    planId: str
    draft: ConditionPlanDraft


class ConfirmConditionPlanRequest(ConditionPlanDraft):
    confirmedBy: str


class ConfirmConditionPlanResponse(BaseModel):
    planId: str
    status: str
    normalizedQuery: dict[str, Any]


class CreateSearchRunRequest(BaseModel):
    caseId: str
    planId: str
    pageBudget: int
    idempotencyKey: str


class CreateSearchRunResponse(BaseModel):
    runId: str
    status: str


class SearchRunStatusResponse(BaseModel):
    runId: str
    status: str
    progress: float
    pageCount: int
    errorSummary: Optional[str] = None


class CandidateCard(BaseModel):
    candidateId: str
    externalIdentityId: str
    name: str
    title: str
    company: str
    location: str
    summary: Optional[str] = None


class SearchRunPageSnapshot(BaseModel):
    pageNo: int
    status: str
    fetchedAt: datetime
    candidates: list[CandidateCard]
    total: int
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None


class SearchRunPagesResponse(BaseModel):
    runId: str
    snapshots: list[SearchRunPageSnapshot]


class ResumeSnapshot(BaseModel):
    id: str
    content: dict[str, Any]


class ResumeAnalysis(BaseModel):
    status: str
    summary: str
    evidenceSpans: list[str]
    riskFlags: list[str]


class Verdict(Enum):
    Match = 'Match'
    Maybe = 'Maybe'
    No = 'No'


class SaveVerdictRequest(BaseModel):
    verdict: Verdict
    reasons: list[str]
    notes: Optional[str] = None
    actorId: str
    resumeSnapshotId: Optional[str] = None


class SaveVerdictResponse(BaseModel):
    candidateId: str
    latestVerdict: Verdict
    updatedAt: datetime


class MaskPolicy(Enum):
    masked = 'masked'
    sensitive = 'sensitive'


class CreateExportRequest(BaseModel):
    caseId: str
    maskPolicy: MaskPolicy
    reason: str
    idempotencyKey: str


class CreateExportResponse(BaseModel):
    exportJobId: str
    status: str
    filePath: Optional[str] = None


class MetricItem(BaseModel):
    name: str
    value: float


class OpsSummaryResponse(BaseModel):
    queue: dict[str, Any]
    failures: dict[str, Any]
    latency: dict[str, Any]
    version: dict[str, Any]
    metrics: list[MetricItem]


class CreateEvalRunRequest(BaseModel):
    suiteId: str
    datasetId: str
    targetVersion: str


class CreateEvalRunResponse(BaseModel):
    evalRunId: str
    status: str


class VerdictRecord(BaseModel):
    verdict: Verdict
    reasons: list[str]
    notes: Optional[str] = None
    actorId: str
    createdAt: datetime


class CandidateDetailResponse(BaseModel):
    candidate: CandidateCard
    resumeSnapshot: ResumeSnapshot
    aiAnalysis: ResumeAnalysis
    verdictHistory: list[VerdictRecord]
