# generated by datamodel-codegen:
#   filename:  platform-api.openapi.yaml
#   timestamp: 2026-03-25T01:02:42+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class CreateCaseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1)
    ownerTeamId: constr(min_length=1)


class CreateCaseResponse(BaseModel):
    caseId: str
    status: str


class CreateJdVersionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rawText: constr(min_length=1)
    source: constr(min_length=1)


class CreateJdVersionResponse(BaseModel):
    jdVersionId: str
    versionNo: int
    status: str


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: constr(min_length=1)
    excerpt: constr(min_length=1)


class StructuredFilters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: conint(ge=1)
    pageSize: conint(ge=1)
    location: list[constr(min_length=1)] | None = None
    degree: int | None = None
    schoolType: int | None = None
    workExperienceRange: int | None = None
    position: constr(min_length=1) | None = None
    workContent: constr(min_length=1) | None = None
    company: constr(min_length=1) | None = None
    school: constr(min_length=1) | None = None


class ConditionPlanDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mustTerms: list[constr(min_length=1)]
    shouldTerms: list[constr(min_length=1)]
    excludeTerms: list[constr(min_length=1)]
    structuredFilters: StructuredFilters
    evidenceRefs: list[EvidenceRef]


class CreateKeywordDraftJobRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jdVersionId: constr(min_length=1)
    modelVersion: constr(min_length=1)
    promptVersion: constr(min_length=1)


class CreateKeywordDraftJobResponse(BaseModel):
    jobId: str
    status: str
    planId: str
    draft: ConditionPlanDraft


class ConfirmConditionPlanRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mustTerms: list[constr(min_length=1)]
    shouldTerms: list[constr(min_length=1)]
    excludeTerms: list[constr(min_length=1)]
    structuredFilters: StructuredFilters
    evidenceRefs: list[EvidenceRef]
    confirmedBy: constr(min_length=1)


class NormalizedQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jd: constr(min_length=1)
    mustTerms: list[constr(min_length=1)]
    shouldTerms: list[constr(min_length=1)]
    excludeTerms: list[constr(min_length=1)]
    structuredFilters: StructuredFilters
    keyword: constr(min_length=1)


class CreateSearchRunRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseId: constr(min_length=1)
    planId: constr(min_length=1)
    pageBudget: conint(ge=1)
    idempotencyKey: constr(min_length=1)


class CreateSearchRunResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    status: str


class SearchRunStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    status: str
    progress: float
    pageCount: int
    errorSummary: str | None = None


class CandidateCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidateId: str
    externalIdentityId: str
    name: str
    title: str
    company: str
    location: str
    summary: str | None = None


class SearchRunPageSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageNo: int
    status: str
    fetchedAt: AwareDatetime
    candidates: list[CandidateCard]
    total: int
    errorCode: str | None = None
    errorMessage: str | None = None


class SearchRunPagesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    snapshots: list[SearchRunPageSnapshot]


class ResumeEducationItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    school: str
    degree: str
    major: str
    startTime: str | None
    endTime: str | None


class ResumeWorkExperienceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company: str
    title: str
    duration: str | None
    startTime: str | None
    endTime: str | None
    summary: str | None


class ResumeProjection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    workYear: int | None
    currentLocation: str | None
    expectedLocation: str | None
    jobState: str | None
    expectedSalary: str | None
    age: int | None
    education: list[ResumeEducationItem]
    workExperience: list[ResumeWorkExperienceItem]
    workSummaries: list[str]
    projectNames: list[str]


class CandidateResumeView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshotId: str
    projection: ResumeProjection


class ResumeAnalysis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    summary: str
    evidenceSpans: list[str]
    riskFlags: list[str]


class Verdict(StrEnum):
    Match = 'Match'
    Maybe = 'Maybe'
    No = 'No'


class SaveVerdictRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verdict: Verdict
    reasons: list[str]
    notes: str | None = None
    actorId: constr(min_length=1)
    resumeSnapshotId: str | None = None


class SaveVerdictResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidateId: str
    latestVerdict: Verdict
    updatedAt: AwareDatetime


class MaskPolicy(StrEnum):
    masked = 'masked'
    sensitive = 'sensitive'


class CreateExportRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    caseId: constr(min_length=1)
    maskPolicy: MaskPolicy
    reason: constr(min_length=1)
    idempotencyKey: constr(min_length=1)


class CreateExportResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exportJobId: str
    status: str
    filePath: str | None = None


class MetricItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    value: float


class SearchRunStatusCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    count: int


class SearchRunFailureCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    count: int


class QueueSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    searchRuns: list[SearchRunStatusCount]


class FailureSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    searchRuns: list[SearchRunFailureCount]


class LatencySummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avgSearchRunSeconds: float


class OpsVersionInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api: str
    apiBuildId: str
    workerBuildId: str
    externalCts: str
    temporalNamespace: str
    temporalUiUrl: str
    temporalVisibilityBackend: str


class OpsSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    queue: QueueSummary
    failures: FailureSummary
    latency: LatencySummary
    version: OpsVersionInfo
    metrics: list[MetricItem]


class TemporalSearchRunDiagnosticResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    workflowId: str
    namespace: str
    taskQueue: str
    appStatus: str
    temporalExecutionFound: bool
    temporalExecutionStatus: str | None = None
    visibilityIndexed: bool
    visibilityBackend: str
    startedAt: AwareDatetime | None = None
    closedAt: AwareDatetime | None = None
    error: str | None = None
    temporalUiUrl: str


class CreateEvalRunRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    suiteId: constr(min_length=1)
    datasetId: constr(min_length=1)
    targetVersion: constr(min_length=1)


class CreateEvalRunResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evalRunId: str
    status: str


class ApiErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    retryable: bool


class ConfirmConditionPlanResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    planId: str
    status: str
    normalizedQuery: NormalizedQuery


class VerdictRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verdict: Verdict
    reasons: list[str]
    notes: str | None = None
    actorId: str
    createdAt: AwareDatetime


class CandidateDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate: CandidateCard
    resumeView: CandidateResumeView
    aiAnalysis: ResumeAnalysis
    verdictHistory: list[VerdictRecord]
