from __future__ import annotations

from typing import Protocol

from cvm_platform.application.dto import (
    AgentRunRecord,
    AuditLogRecord,
    CandidateRecord,
    EvalRunRecord,
    ExportJobRecord,
    JDVersionRecord,
    ResumeAnalysisRecord,
    ResumeSnapshotRecord,
    VerdictHistoryRecord,
    CaseRecord,
)


class CasesRepository(Protocol):
    def get(self, case_id: str) -> CaseRecord | None: ...

    def save(self, case: CaseRecord) -> CaseRecord: ...


class PlansRepository(Protocol):
    def count_versions_for_case(self, case_id: str) -> int: ...

    def deactivate_versions(self, case_id: str) -> None: ...

    def get_jd_version(self, case_id: str, jd_version_id: str) -> JDVersionRecord | None: ...

    def save_jd_version(self, jd_version: JDVersionRecord) -> JDVersionRecord: ...


class AgentRunsRepository(Protocol):
    def find_by_idempotency_key(self, idempotency_key: str) -> AgentRunRecord | None: ...

    def get_run(self, run_id: str) -> AgentRunRecord | None: ...

    def save_run(self, run: AgentRunRecord) -> AgentRunRecord: ...

    def list_runs(self) -> list[AgentRunRecord]: ...

    def count_by_status(self) -> dict[str, int]: ...

    def count_failures_by_error_code(self) -> dict[str | None, int]: ...

    def list_finished_runs(self) -> list[AgentRunRecord]: ...


class CandidatesRepository(Protocol):
    def find_by_case_and_external_identity(self, case_id: str, external_identity_id: str) -> CandidateRecord | None: ...

    def get_candidate(self, candidate_id: str) -> CandidateRecord | None: ...

    def save_candidate(self, candidate: CandidateRecord) -> CandidateRecord: ...

    def find_resume_snapshot_by_source_hash(self, candidate_id: str, source_hash: str) -> ResumeSnapshotRecord | None: ...

    def get_resume_snapshot(self, snapshot_id: str) -> ResumeSnapshotRecord | None: ...

    def save_resume_snapshot(self, snapshot: ResumeSnapshotRecord) -> ResumeSnapshotRecord: ...

    def get_latest_analysis(self, snapshot_id: str) -> ResumeAnalysisRecord | None: ...

    def save_resume_analysis(self, analysis: ResumeAnalysisRecord) -> ResumeAnalysisRecord: ...

    def list_verdict_history(self, candidate_id: str) -> list[VerdictHistoryRecord]: ...

    def save_verdict_history(self, history: VerdictHistoryRecord) -> VerdictHistoryRecord: ...

    def list_exportable_candidates(self, case_id: str) -> list[CandidateRecord]: ...

    def count_candidates(self) -> int: ...


class ExportsRepository(Protocol):
    def find_by_idempotency_key(self, idempotency_key: str) -> ExportJobRecord | None: ...

    def save_export_job(self, export_job: ExportJobRecord) -> ExportJobRecord: ...


class EvalRunsRepository(Protocol):
    def save_eval_run(self, eval_run: EvalRunRecord) -> EvalRunRecord: ...


class AuditLogRepository(Protocol):
    def save_audit_log(self, audit_log: AuditLogRecord) -> AuditLogRecord: ...


class PlatformUnitOfWork(Protocol):
    cases: CasesRepository
    plans: PlansRepository
    agent_runs: AgentRunsRepository
    candidates: CandidatesRepository
    exports: ExportsRepository
    eval_runs: EvalRunsRepository
    audit_logs: AuditLogRepository

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
